theme: jekyll-theme-slate
title: The homepage of Kodai Nedachi, introducing myself
description: What you will find here are links to Hokudai boy.
plugins:
  - jemoji
url: "https://kodai0424.github.io/&quot;
markdown: kramdown
