theme: jekyll-theme-slate
title: The homepage of Kodai Nedachi, introducing myself
description: What you will find here are links to projects, publications, and repositories related to the former.
plugins:
  - jemoji
url: "https://michaelschiltz.github.io/&quot;
markdown: kramdown
